use anyhow::{Context, Result};
use cargo_toml::{Dependency, Manifest};
use regex::Regex;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use syn::{parse_file, Item};

#[derive(Debug, Clone)]
pub struct CrateInfo {
    pub name: String,
    pub path: PathBuf,
    pub main_path: PathBuf,
    pub strategy: TransformStrategy,
    pub dependencies: BTreeMap<String, DepInfo>,
    /// If true, this crate has a library (lib.rs) that the binary may depend on
    pub has_library: bool,
    /// Version of the crate (for adding as dependency)
    pub version: Option<String>,
    /// Files generated by build script (path relative to OUT_DIR -> content)
    pub build_script_outputs: BTreeMap<String, String>,
    /// If true, main.rs has internal `mod` declarations that require copying source files
    pub has_internal_modules: bool,
    /// Source directory path (usually src/)
    pub src_dir: PathBuf,
}

#[derive(Debug, Clone)]
pub struct DepInfo {
    pub version: Option<String>,
    pub features: Vec<String>,
    #[allow(dead_code)]
    pub optional: bool,
}

#[derive(Debug, Clone)]
pub enum TransformStrategy {
    /// Simple fn main() - can be extracted directly
    SimpleMain,
    /// Has #[...] attributes on main - needs special handling
    AttributedMain { attrs: Vec<String> },
    /// Uses build script generated code - needs to run build first
    BuildScriptMain { attrs: Vec<String> },
    /// Uses uucore::bin! macro (uutils coreutils pattern)
    UucoreBinMacro { crate_name: String },
    /// Has a library interface we can use
    #[allow(dead_code)]
    LibraryInterface { entry_fn: String },
    /// Cannot be transformed automatically
    Unsupported { reason: String },
}

pub fn analyze_crate(path: &Path) -> Result<CrateInfo> {
    let cargo_toml_path = path.join("Cargo.toml");
    let manifest = Manifest::from_path(&cargo_toml_path).context("Failed to parse Cargo.toml")?;

    let name = manifest
        .package
        .as_ref()
        .map(|p| p.name.clone())
        .unwrap_or_else(|| "unknown".to_string());

    // Find main.rs
    let main_path = find_main_rs(path, &manifest)?;

    // Analyze main() function
    let source = fs::read_to_string(&main_path).context("Failed to read main.rs")?;
    let strategy = analyze_main_function(&source)?;

    // Collect dependencies with full info, filtering out path-based (workspace) dependencies
    let dependencies: BTreeMap<String, DepInfo> = manifest
        .dependencies
        .iter()
        .filter_map(|(name, dep)| {
            let (actual_name, info) = match dep {
                Dependency::Simple(version) => (
                    name.clone(),
                    Some(DepInfo {
                        version: Some(version.clone()),
                        features: vec![],
                        optional: false,
                    }),
                ),
                Dependency::Detailed(detail) => {
                    // Skip path-based dependencies (workspace members, local crates)
                    if detail.path.is_some() {
                        return None;
                    }
                    // Skip git dependencies for now (they need special handling)
                    if detail.git.is_some() {
                        return None;
                    }
                    // Skip optional dependencies (feature-gated, not needed by default)
                    if detail.optional {
                        return None;
                    }
                    // Use the actual package name if it's different (renamed dependency)
                    let actual_name = detail.package.clone().unwrap_or_else(|| name.clone());
                    (
                        actual_name,
                        Some(DepInfo {
                            version: detail.version.clone(),
                            features: detail.features.clone(),
                            optional: detail.optional,
                        }),
                    )
                }
                Dependency::Inherited(inherited) => {
                    // Inherited dependencies without version info can't be resolved
                    // Skip them unless we have workspace context
                    if inherited.workspace {
                        return None;
                    }
                    // Skip optional dependencies
                    if inherited.optional {
                        return None;
                    }
                    (
                        name.clone(),
                        Some(DepInfo {
                            version: None,
                            features: inherited.features.clone(),
                            optional: inherited.optional,
                        }),
                    )
                }
            };
            info.map(|i| (actual_name, i))
        })
        .collect();

    // Check if this crate has a library component
    let has_library = path.join("src/lib.rs").exists() || manifest.lib.is_some();

    // Get version from manifest
    let version = manifest
        .package
        .as_ref()
        .and_then(|p| p.version.get().ok())
        .map(|v| v.to_string());

    // Check if main.rs has internal module declarations
    let has_internal_modules = has_mod_declarations(&source);

    // Determine the source directory
    let src_dir = main_path.parent().unwrap_or(path).to_path_buf();

    Ok(CrateInfo {
        name,
        path: path.to_path_buf(),
        main_path,
        strategy,
        dependencies,
        has_library,
        version,
        build_script_outputs: BTreeMap::new(),
        has_internal_modules,
        src_dir,
    })
}

/// Check if source code has internal `mod` declarations (not `mod name;` but actual modules)
fn has_mod_declarations(source: &str) -> bool {
    // Look for `mod name;` patterns (external module declarations)
    // These indicate the crate has separate .rs files that need to be copied
    let mod_pattern = Regex::new(r"(?m)^mod\s+[a-zA-Z_][a-zA-Z0-9_]*\s*;").unwrap();
    mod_pattern.is_match(source)
}

fn find_main_rs(crate_path: &Path, manifest: &Manifest) -> Result<PathBuf> {
    // First check if there's a [[bin]] entry with an explicit path
    for bin in &manifest.bin {
        if let Some(path) = &bin.path {
            let bin_path = crate_path.join(path);
            if bin_path.exists() {
                return Ok(bin_path);
            }
        }
    }

    // Default candidates
    let candidates = [
        crate_path.join("src/main.rs"),
        crate_path.join("src/bin/main.rs"),
    ];

    for candidate in candidates {
        if candidate.exists() {
            return Ok(candidate);
        }
    }

    anyhow::bail!("Could not find main.rs in {:?}", crate_path)
}

fn analyze_main_function(source: &str) -> Result<TransformStrategy> {
    // Check for uucore::bin! macro pattern (uutils coreutils individual utilities)
    // Pattern: uucore::bin!(crate_name);
    if let Ok(uucore_pattern) = Regex::new(r"uucore::bin!\s*\(\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\)") {
        if let Some(captures) = uucore_pattern.captures(source) {
            if let Some(crate_match) = captures.get(1) {
                return Ok(TransformStrategy::UucoreBinMacro {
                    crate_name: crate_match.as_str().to_string(),
                });
            }
        }
    }

    // Check for include! macro which indicates build script generated code
    let uses_build_script = source.contains("include!(") && source.contains("OUT_DIR");

    let file = parse_file(source).context("Failed to parse Rust source")?;

    for item in &file.items {
        if let Item::Fn(func) = item {
            if func.sig.ident == "main" {
                // Check for attributes (excluding doc comments)
                let attrs: Vec<String> = func
                    .attrs
                    .iter()
                    .filter(|a| !a.path().is_ident("doc"))
                    .map(|a| {
                        // Convert path segments to string
                        a.path()
                            .segments
                            .iter()
                            .map(|s| s.ident.to_string())
                            .collect::<Vec<_>>()
                            .join("::")
                    })
                    .collect();

                if uses_build_script {
                    return Ok(TransformStrategy::BuildScriptMain { attrs });
                } else if attrs.is_empty() {
                    return Ok(TransformStrategy::SimpleMain);
                } else {
                    return Ok(TransformStrategy::AttributedMain { attrs });
                }
            }
        }
    }

    // No main found
    Ok(TransformStrategy::Unsupported {
        reason: "No main() function found".to_string(),
    })
}

/// Run cargo build on a crate to generate build script outputs, then capture them
pub fn run_build_script(crate_path: &Path, crate_name: &str) -> Result<BTreeMap<String, String>> {
    println!("    Running build script for {}...", crate_name);

    // Copy .cargo/config.toml if it exists in the current directory or parents
    // This is needed for NixOS and other environments with custom linker settings
    copy_cargo_config_to(crate_path)?;

    // Run cargo build to trigger the build script
    let output = Command::new("cargo")
        .args(["build", "--message-format=json"])
        .current_dir(crate_path)
        .output()
        .context("Failed to run cargo build")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        anyhow::bail!("Build script failed: {}", stderr);
    }

    // Parse the JSON output to find OUT_DIR for this specific crate
    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut out_dir: Option<PathBuf> = None;

    for line in stdout.lines() {
        if let Ok(json) = serde_json::from_str::<serde_json::Value>(line) {
            // Look for build-script-executed message for our crate
            if json.get("reason").and_then(|r| r.as_str()) == Some("build-script-executed") {
                // Check if this is for our crate by examining the package_id
                let package_id = json
                    .get("package_id")
                    .and_then(|p| p.as_str())
                    .unwrap_or("");
                if package_id.contains(&format!("#{}@", crate_name))
                    || package_id.contains(&format!("/{}/", crate_name))
                    || package_id.ends_with(&format!("#{}", crate_name))
                {
                    if let Some(out) = json.get("out_dir").and_then(|d| d.as_str()) {
                        out_dir = Some(PathBuf::from(out));
                        break;
                    }
                }
            }
        }
    }

    // If we didn't find it by package_id, try to find it in the target directory
    if out_dir.is_none() {
        let build_dir = crate_path.join("target/debug/build");
        if build_dir.exists() {
            for entry in fs::read_dir(&build_dir)? {
                let entry = entry?;
                let name = entry.file_name().to_string_lossy().to_string();
                if name.starts_with(&format!("{}-", crate_name)) {
                    let candidate = entry.path().join("out");
                    if candidate.exists() {
                        out_dir = Some(candidate);
                        break;
                    }
                }
            }
        }
    }

    let out_dir = out_dir.context("Could not find OUT_DIR from build output")?;

    // Collect all .rs files from OUT_DIR
    let mut outputs = BTreeMap::new();
    if out_dir.exists() {
        collect_rs_files(&out_dir, &out_dir, &mut outputs)?;
    }

    Ok(outputs)
}

/// Recursively collect .rs files from a directory
fn collect_rs_files(base: &Path, dir: &Path, outputs: &mut BTreeMap<String, String>) -> Result<()> {
    if !dir.is_dir() {
        return Ok(());
    }

    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            collect_rs_files(base, &path, outputs)?;
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            let relative = path
                .strip_prefix(base)
                .unwrap_or(&path)
                .to_string_lossy()
                .to_string();
            let content = fs::read_to_string(&path)?;
            outputs.insert(relative, content);
        }
    }

    Ok(())
}

/// Copy .cargo/config.toml from current directory or parents to a target directory
fn copy_cargo_config_to(dest_dir: &Path) -> Result<()> {
    let mut search_dir = std::env::current_dir()?;

    loop {
        let cargo_config = search_dir.join(".cargo").join("config.toml");
        if cargo_config.exists() {
            let dest_cargo_dir = dest_dir.join(".cargo");
            fs::create_dir_all(&dest_cargo_dir)?;
            fs::copy(&cargo_config, dest_cargo_dir.join("config.toml"))?;
            return Ok(());
        }

        // Also check for config (without .toml extension)
        let cargo_config_alt = search_dir.join(".cargo").join("config");
        if cargo_config_alt.exists() {
            let dest_cargo_dir = dest_dir.join(".cargo");
            fs::create_dir_all(&dest_cargo_dir)?;
            fs::copy(&cargo_config_alt, dest_cargo_dir.join("config"))?;
            return Ok(());
        }

        // Move to parent directory
        if let Some(parent) = search_dir.parent() {
            search_dir = parent.to_path_buf();
        } else {
            break;
        }
    }

    // No cargo config found, which is fine
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_analyze_simple_main() {
        let source = r#"
fn main() {
    println!("Hello, world!");
}
"#;
        let strategy = analyze_main_function(source).unwrap();
        assert!(matches!(strategy, TransformStrategy::SimpleMain));
    }

    #[test]
    fn test_analyze_attributed_main() {
        let source = r#"
#[tokio::main]
async fn main() {
    println!("Hello, async world!");
}
"#;
        let strategy = analyze_main_function(source).unwrap();
        assert!(matches!(strategy, TransformStrategy::AttributedMain { .. }));
    }

    #[test]
    fn test_analyze_no_main() {
        let source = r#"
fn not_main() {
    println!("Hello!");
}
"#;
        let strategy = analyze_main_function(source).unwrap();
        assert!(matches!(strategy, TransformStrategy::Unsupported { .. }));
    }
}
